### ISSUE TITLE
Not able to generate the QR code update 

### ISSUE THREAD

**Issue by twfiles** [invite-frey/is-woo-payment-fps#1]
My woocomerce site are not able to generate the qr Code after the update 5 days ago

**Comment by invite-frey** [comment]
Have you configured it to use e-mail address, phone number or FPS id as Payee identification? Does it generate a QR Code at all, or is the generated QR Code invalid?

**Comment by twfiles** [comment]
I had tried to enter phone number or FPS id with the bank code, but it just shows a deadlink image on the location where the QR code should be placed

**Comment by twfiles** [comment]
> Have you configured it to use e-mail address, phone number or FPS id as Payee identification? Does it generate a QR Code at all, or is the generated QR Code invalid?

Our client reported that even if the qr code is generated, the qr code is invalid (i have 3 woocommerce site, 2 of them cannot be generated while 1 can generate but the qr is invalid

**Comment by invite-frey** [comment]
>  2 of them cannot be generated 

Make sure WP_DEBUG is set to false in wp-config.php as follows:

`define( 'WP_DEBUG', false );`

**Comment by invite-frey** [comment]
> the qr code is invalid 

Did some trouble shooting on this, and the HKQR app seems to validate all QR codes generated just fine, as well as most bank apps I tried also. For some reason the HSBC app complains about an invalid QR code depending on what amount has been entered. I need to look more closely at this. If you are able to confirm if this problem occurs also with other apps, not just the HSBC app it would be helpful... 

Also if you are using a phone number as FPS proxy id, make sure it is **exactly** in the following format:

`+852-xxxxxxxx`

...where xxxxxxxx is an 8 digit HK mobile phone number with NO spaces and + and - signs exactly as above...

**Comment by invite-frey** [comment]
Just released v1.2 which hopefully fixes "invalid QR code" problems... Please upgrade and let me know if that fixes your invalid QR code issues as well. The checksum hex string was embedded as lower case letters into the QR code and it turns out some apps only accept the checksum in all upper case letters.

**Comment by twfiles** [comment]
> > 2 of them cannot be generated
> 
> Make sure WP_DEBUG is set to false in wp-config.php as follows:
> 
> `define( 'WP_DEBUG', false );`

had just checked the config file and WP_DEBUG is already set to false
but still the qr cannot be generated, even i had update to v1.2
the attach image as reference:

we are using PHP7.0.9 with Woocommerce 4.2.0 and wordpress 5.4.2
![image](https://user-images.githubusercontent.com/1480850/91711593-b320c300-ebb8-11ea-9971-6aec4bc3067d.png)

**Comment by twfiles** [comment]
> Just released v1.2 which hopefully fixes "invalid QR code" problems... Please upgrade and let me know if that fixes your invalid QR code issues as well. The checksum hex string was embedded as lower case letters into the QR code and it turns out some apps only accept the checksum in all upper case letters.

For that website which can generate the QRcode, I was using Hang Seng Bank Apps for FPS payment, and after version update its able to pay via QR code again

**Comment by twfiles** [comment]
> > > 2 of them cannot be generated
> > 
> > 
> > Make sure WP_DEBUG is set to false in wp-config.php as follows:
> > `define( 'WP_DEBUG', false );`
> 
> had just checked the config file and WP_DEBUG is already set to false
> but still the qr cannot be generated, even i had update to v1.2
> the attach image as reference:
> 
> we are using PHP7.0.9 with Woocommerce 4.2.0 and wordpress 5.4.2
> ![image](https://user-images.githubusercontent.com/1480850/91711593-b320c300-ebb8-11ea-9971-6aec4bc3067d.png)
Another website still not able to generate the QRCode using wordpress 5.3.4 with Woocommerce 4.2.0 :
![image](https://user-images.githubusercontent.com/1480850/91713171-d731d380-ebbb-11ea-9766-146ce61c3dd3.png)

**Comment by invite-frey** [comment]
> > Just released v1.2 which hopefully fixes "invalid QR code" problems... Please upgrade and let me know if that fixes your invalid QR code issues as well. The checksum hex string was embedded as lower case letters into the QR code and it turns out some apps only accept the checksum in all upper case letters.
> 
> For that website which can generate the QRcode, I was using Hang Seng Bank Apps for FPS payment, and after version update its able to pay via QR code again

Great! So the invalid QR Code problem is solved.

**Comment by invite-frey** [comment]
> had just checked the config file and WP_DEBUG is already set to false
> but still the qr cannot be generated, even i had update to v1.2

I just released v1.3, trying to output the QR Code at an earlier stage during the WP startup. The problem is probably that there is something in your setup that causes Wordpress to output something before the script sends out the image header, which causes the image to break. Let me know if v1.3 is any help. If not, I have to try a completely different approach.

**Comment by twfiles** [comment]
> > had just checked the config file and WP_DEBUG is already set to false
> > but still the qr cannot be generated, even i had update to v1.2
> 
> I just released v1.3, trying to output the QR Code at an earlier stage during the WP startup. The problem is probably that there is something in your setup that causes Wordpress to output something before the script sends out the image header, which causes the image to break. Let me know if v1.3 is any help. If not, I have to try a completely different approach.

After update my website are able to generate the QRCode! Thanks for your help!

**Comment by twfiles** [comment]
> > had just checked the config file and WP_DEBUG is already set to false
> > but still the qr cannot be generated, even i had update to v1.2
> 
> I just released v1.3, trying to output the QR Code at an earlier stage during the WP startup. The problem is probably that there is something in your setup that causes Wordpress to output something before the script sends out the image header, which causes the image to break. Let me know if v1.3 is any help. If not, I have to try a completely different approach.

Just a little bit mention, in v1.3, there are some line breaks after the closing ?> tag at the file "hong-kong-fps-woo-payment.php", which may makes some automated generated sitemap xml not working. I had removed it myself. Once again thank you for your help!

**Comment by twfiles** [comment]
> > had just checked the config file and WP_DEBUG is already set to false
> > but still the qr cannot be generated, even i had update to v1.2
> 
> I just released v1.3, trying to output the QR Code at an earlier stage during the WP startup. The problem is probably that there is something in your setup that causes Wordpress to output something before the script sends out the image header, which causes the image to break. Let me know if v1.3 is any help. If not, I have to try a completely different approach.

Sorry for reopening the issue, theres another weird issue that our client just report that the qr code cannot be shown on mobile browsers (i wonder why they need the qr code on mobile phone..) . I had tried using my android 10 with google chrome, and it cannot be show even i used the request desktop site function.
But for windows 10 and google chrome, the qr code is working fine.

**Comment by invite-frey** [comment]
Try updating to the newest version 1.41. Then go into Woocommerce -> Settings -> Payments -> Hong Kong FPS. There is a new setting at the bottom of the page called "Write QRCode to disk", check the box to activate this function and test again. Please empty all browser caches after changing this setting. This option generates a QRCode for every combination of recipient and payment amount, stores it to disk and serves it as standard picture file. Might leave that as the default option if too many browsers get confused by the dynamically generated QR Code.

**Comment by twfiles** [comment]
> Try updating to the newest version 1.41. Then go into Woocommerce -> Settings -> Payments -> Hong Kong FPS. There is a new setting at the bottom of the page called "Write QRCode to disk", check the box to activate this function and test again. Please empty all browser caches after changing this setting. This option generates a QRCode for every combination of recipient and payment amount, stores it to disk and serves it as standard picture file. Might leave that as the default option if too many browsers get confused by the dynamically generated QR Code.

its working right now, thanks

fyi, there's still two empty line after the close tag of hong-kong-fps-woo-payment.php, i had removed it by myself.
Thanks for your help.
